correção do erro:
api/_lib/auth.ts(175,25): error TS2344: Type 'SessionRecord[]' does not satisfy the constraint 'boolean'.
api/_lib/auth.ts(191,19): error TS7053: Element implicitly has an 'any' type because expression of type '0' can't be used to index type 'any[][] | Record<string, any>[] | FullQueryResults<boolean>'.